# Generated by Django 5.2 on 2025-04-15 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='UUID',
                    ),
                ),
                (
                    'job_id',
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, verbose_name='Job ID'
                    ),
                ),
                (
                    'content',
                    models.TextField(
                        help_text='The content of the reminder', verbose_name='Content'
                    ),
                ),
                (
                    'scheduled_time',
                    models.DateTimeField(
                        help_text='The time when the reminder should be sent',
                        verbose_name='Scheduled Time',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'PENDING'),
                            ('ENQUEUED', 'ENQUEUED'),
                            ('COMPLETED', 'COMPLETED'),
                            ('FAILED', 'FAILED'),
                        ],
                        db_index=True,
                        default='PENDING',
                        max_length=50,
                        verbose_name='Status',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='database.tenantorm'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders',
            },
        ),
        migrations.CreateModel(
            name='ReminderRecipientORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='UUID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'PENDING'), ('SENT', 'SENT')],
                        default='PENDING',
                        max_length=50,
                        verbose_name='Status',
                    ),
                ),
                (
                    'phone_number',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reminder_recipients',
                        to='database.phonenumberorm',
                        verbose_name='Phone Number',
                    ),
                ),
                (
                    'reminder',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recipients',
                        to='database.reminderorm',
                        verbose_name='Reminder',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reminder Recipient',
                'verbose_name_plural': 'Reminder Recipients',
                'db_table': 'reminder_recipients',
            },
        ),
    ]
