# Generated by Django 5.2 on 2025-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0002_reminderorm_reminderrecipientorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderrecipientorm',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED')],
                default='PENDING',
                max_length=50,
                verbose_name='Status',
            ),
        ),
    ]
