# Generated by Django 5.2 on 2025-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0003_alter_reminderrecipientorm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderorm',
            name='job_id',
        ),
        migrations.AddField(
            model_name='reminderorm',
            name='scheduled_job_id',
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, verbose_name='Scheduled Job ID'
            ),
        ),
    ]
