# Generated by Django 5.2 on 2025-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0004_remove_reminderorm_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderorm',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'PENDING'),
                    ('ENQUEUED', 'ENQUEUED'),
                    ('IN_PROGRESS', 'IN_PROGRESS'),
                    ('COMPLETED', 'COMPLETED'),
                    ('FAILED', 'FAILED'),
                ],
                db_index=True,
                default='PENDING',
                max_length=50,
                verbose_name='Status',
            ),
        ),
    ]
