name: wa-reminders

volumes:
  postgres_data:
  mongo_data:
  mongo_config:


services:
  redis:
    image: redis:7

  postgres:
    image: postgres:15.7
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    logging:
      driver: none
    ports:
      - "8025:8025"
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - mailhog
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /start

  mongo:
    image: mongo:noble
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH: false



