# -*- encoding: utf-8 -*-
from decimal import Decimal

from config.settings.components import env

ALLOWED_TENANTS_LIMIT = env.int('ALLOWED_TENANTS_LIMIT', default=5)

#
# PAYMENTS
#
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET')
STRIPE_CONNECT_WEBHOOK_SECRET = env('STRIPE_CONNECT_WEBHOOK_SECRET')

STRIPE_TEST_PUBLISHABLE_KEY = env('STRIPE_TEST_PUBLISHABLE_KEY')
STRIPE_TEST_SECRET_KEY = env('STRIPE_TEST_SECRET_KEY')
STRIPE_TEST_WEBHOOK_SECRET = env('STRIPE_TEST_WEBHOOK_SECRET')
STRIPE_TEST_CONNECT_WEBHOOK_SECRET = env('STRIPE_TEST_CONNECT_WEBHOOK_SECRET')

#  Stripe Reg. fee: 3.60% + 3$
#  Xiberty fee: 0.04%
# -------------------------
#  Total fee      : 4.0% + 3$ over the total amount
STRIPE_FEE_PERCENT = Decimal(0.004)  # 0.4 %
STRIPE_TEST_FEE_PERCENT = Decimal(0.004)  # 0.4 %

PUSHER_APP_ID = env('PUSHER_APP_ID')
PUSHER_KEY = env('PUSHER_KEY')
PUSHER_SECRET = env('PUSHER_SECRET')
PUSHER_HOST = env('PUSHER_HOST')
