# -*- coding: utf-8 -*-
from src.common.domain.enums.auth import AuthenticationMethod
from src.common.domain.enums.countries import CountryIsoCode
from src.common.domain.enums.currencies import CurrencyCode
from src.common.domain.enums.locales import Language, TimeZone


DEFAULT_PENDING_ACTION_EXPIRATION_IN_MINUTES = 20
DEFAULT_PENDING_ACTION_USAGE_LIMIT = 1
DEFAULT_PENDING_ACTION_SESSION_USAGE_LIMIT = 4
UNIQUE_USAGE_LIMIT = 1

INSTANCE_DELETED_RESPONSE = None

DEFAULT_MEMBERSHIP_PLAN_GRACE_PERIOD_IN_DAYS = 5
DEFAULT_MEMBERSHIP_PLAN_STUDENTS_NUMBER = 1
DEFAULT_MEMBERSHIP_PLAN_PASSES_NUMBER = 4
DEFAULT_MEMBERSHIP_PLAN_VALIDITY_DAYS = 90
DEFAULT_MEMBERSHIP_PLAN_TIME_MULTIPLIER = 1
DEFAULT_SESSION_TOLERANCE_IN_MINUTES = 20

ONE_WEEK_DAYS = 7
ONE_MONTH = 1
ONE_DAY = 1

DEFAULT_NEXT_SESSIONS_IN_MINUTES = 12 * 60  # 12 hours

DEFAULT_TIMEZONE = TimeZone.MEXICO_CITY
DEFAULT_LANGUAGE = Language.ES
DEFAULT_CURRENCY_CODE = CurrencyCode.MXN
DEFAULT_COUNTRY_ISO_CODE = CountryIsoCode.MEXICO
DEFAULT_PENDING_PAYMENTS = 2
DEFAULT_ENROLLMENT_MULTIPLIER = 1
DEFAULT_CHECKIN_WINDOW_IN_MINUTES = 60
DEFAULT_GRACE_PERIOD_DAYS = 5
DEFAULT_MIN_PASSES_BALANCE = 2
DEFAULT_MAX_FREE_TRIALS = 1  # this value is queried by lapse in days
DEFAULT_FREE_TRIALS_LAPSE_IN_DAYS = 365  # 1 year, make this configurable later

DEFAULT_MEXICO_PREFIX = 1

DEFAULT_AUTHENTICATION_METHODS = [AuthenticationMethod.EMAIL, AuthenticationMethod.WHATSAPP]
DEFAULT_WHATSAPP_API_SESSION = 'default'

DEFAULT_INITIAL_PAGE = 1
DEFAULT_PAGINATION_PAGE_SIZE = 25
DEFAULT_PAGINATION_LOOKUP_FIELD = '-created_at'

DEFAULT_SESSION_REDEMPTION_SUB_PATH = 'actions/session'
DEFAULT_EMAIL_VERIFICATION_SUB_PATH = 'actions/email-verification'
DEFAULT_PHONE_VERIFICATION_SUB_PATH = 'actions/phone-verification'

DEFAULT_GENERATED_EMAILS_DOMAIN = 'inbox.collectives.pro'

DEFAULT_NEXT_SESSIONS_IN_HOURS = 6
DEFAULT_PREV_SESSIONS_IN_HOURS = 12
DEFAULT_SCHEDULE_SESSION_IN_DAYS = 90

DEFAULT_CHECKIN_FROM_SESSIONS_IN_HOURS = 6
DEFAULT_CHECKIN_UNTIL_SESSIONS_IN_HOURS = 6

DEFAULT_NUM_WHAPSAPP_SESSIONS = 1

PHONE_NUMBER_PREFIXES_MAP = {
    CountryIsoCode.MEXICO: 1,
    CountryIsoCode.BRAZIL: 9,
}
